### PR TITLE
UserEntityTypeConfig added

### PR DESCRIPTION
**Pull request by Munzir32**

### CODE REVIEW

**Comment by Munzir32** [comment]
UserEntityTypeConfig added

**Comment by Munzir32** [comment]
Changes made

**Review by absyinka — CHANGES_REQUESTED** [review]
Replace your current implementation with the below

```
public void Configure(EntityTypeBuilder<Role> builder)
{
    builder.ToTable("Roles");
    builder.HasKey(r => r.Id);
    builder.Property(r => r.RoleName).IsRequired().HasMaxLength(50);
    builder.Property(r => r.Description).IsRequired().HasMaxLength(100);

    builder.HasMany(r => r.Users)
        .WithOne(u => u.Role)
        .HasForeignKey(u => u.RoleId);
}

```
So above the following was implemented:

    Set the table name for the Role entity to "Roles".
    Set the primary key for the Role entity to the Id property.
    Set the RoleName and Description properties to be required fields and set their maximum lengths.
    Use HasMany() to configure the one-to-many relationship between Role and User.
    Use WithOne() to specify the navigation property in the User entity that corresponds to the Role entity, which is Role.
    Use HasForeignKey() to specify the foreign key property to use for the relationship, which is RoleId in the User entity.

**Review by absyinka — CHANGES_REQUESTED** [review]
Replace your implementation with the below

```public void Configure(EntityTypeBuilder<User> builder)
{
    builder.ToTable("Users");
    builder.HasKey(u => u.Id);
    builder.Property(u => u.UserName).IsRequired().HasMaxLength(10);
    builder.Property(u => u.Email).IsRequired();
    builder.Property(u => u.RoleId).IsRequired();

    builder.HasOne(u => u.Role)
        .WithMany(r => r.Users)
        .HasForeignKey(u => u.RoleId);
}```

**Comment by Munzir32** [comment]
done

**Review by absyinka — APPROVED** [review]

**Pull request merged**
